[package]
name = "tuimer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
notify-rust = "4"
ratatui = "0.29"
# TODO: I'm interested in trying this out for making a list of timers
# tui-widget-list = "0.12"
